# This is just for reference. travis ci is now a paid service so we will use github actions instead.
sudo: required
services:
  - docker
before_install:
  - docker build -t singiankay/docker-react -f ./frontend/Dockerfile.dev .
script:
  - docker run -e CI=true singiankay/docker-react npm run test -- --coverage