# DEPRECATED: This workflow is no longer active
# Elastic Beanstalk has been replaced with ECS and EKS deployments
# See .github/workflows/ecs-deploy.yml and .github/workflows/eks-deploy.yml for active workflows
#
# Issues with this workflow:
# - Dockerrun.aws.json version compatibility issues
# - Container startup failures (503 errors)
# - AWS deprioritizing Elastic Beanstalk in favor of ECS/EKS
#
# Last working deployment: Never fully functional
# Deprecated on: 2025-10-04
# Reason: Switched to modern container orchestration (ECS/EKS)

name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}-
            ${{ runner.os }}-buildx-

      - name: Build the Docker image
        run: docker build -t docker-react-test -f ./frontend/Dockerfile.dev ./frontend

      - name: Run tests
        run: docker run -e CI=true docker-react-test npm run test -- --coverage

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::185157186506:role/GithubActionsElasticBeanStalkRole
          aws-region: ap-southeast-1

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build, tag, and push image to ECR
      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker-react
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ./frontend/Dockerfile ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # Generate unique version label once
      - name: Generate unique version label
        id: vars
        run: echo "VERSION_LABEL=${GITHUB_SHA::8}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      # Create deployment package with Dockerfile
      - name: Create deployment package
        run: |
          # Copy Dockerfile to root for Elastic Beanstalk
          cp frontend/Dockerfile ./Dockerfile
          cp frontend/nginx.conf ./nginx.conf
          cp -r frontend/src ./src
          cp frontend/package.json ./package.json
          cp frontend/vite.config.js ./vite.config.js
          cp frontend/index.html ./index.html
          cp frontend/eslint.config.js ./eslint.config.js
          
          # Create .dockerignore
          echo "node_modules" > .dockerignore
          echo ".git" >> .dockerignore
          echo "*.md" >> .dockerignore
          
          zip -r $VERSION_LABEL.zip Dockerfile nginx.conf src package.json vite.config.js index.html eslint.config.js .dockerignore

      - name: Upload to S3
        run: |
          aws s3 cp $VERSION_LABEL.zip s3://elasticbeanstalk-ap-southeast-1-185157186506/dockerrun/$VERSION_LABEL.zip

      # Create application if missing
      - name: Ensure application exists
        run: |
          if ! aws elasticbeanstalk describe-applications \
            --application-names docker-react \
            --query "Applications[0].ApplicationName" --output text 2>/dev/null | grep -q docker-react; then
            echo "Application not found. Creating docker-react..."
            aws elasticbeanstalk create-application --application-name docker-react
          else
            echo "Application already exists."
          fi

      # Verify EC2 IAM role exists (must be created manually)
      - name: Verify EC2 IAM Role
        run: |
          echo "Checking IAM role and instance profile..."
          echo "Current AWS identity:"
          aws sts get-caller-identity
          
          # Check if role exists
          if aws iam get-role --role-name ElasticBeanstalk-EC2-Role 2>/dev/null; then
            echo "✅ IAM role exists."
          else
            echo "❌ IAM role 'ElasticBeanstalk-EC2-Role' does not exist."
            echo "Debugging - listing all roles:"
            aws iam list-roles --query "Roles[?contains(RoleName, 'ElasticBeanstalk')]"
            echo ""
            echo "Please create it manually using these commands:"
            echo "aws iam create-role --role-name ElasticBeanstalk-EC2-Role --assume-role-policy-document '{\"Version\": \"2012-10-17\", \"Statement\": [{\"Effect\": \"Allow\", \"Principal\": {\"Service\": \"ec2.amazonaws.com\"}, \"Action\": \"sts:AssumeRole\"}]}'"
            echo "aws iam attach-role-policy --role-name ElasticBeanstalk-EC2-Role --policy-arn arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier"
            echo "aws iam attach-role-policy --role-name ElasticBeanstalk-EC2-Role --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
            exit 1
          fi
          
          # Check if instance profile exists using list command (more reliable)
          echo "Checking instance profile..."
          INSTANCE_PROFILE_EXISTS=$(aws iam list-instance-profiles --query "InstanceProfiles[?InstanceProfileName=='ElasticBeanstalk-EC2-Role']" --output text)
          
          if [ -n "$INSTANCE_PROFILE_EXISTS" ]; then
            echo "✅ Instance profile exists and is ready."
          else
            echo "❌ Instance profile 'ElasticBeanstalk-EC2-Role' does not exist."
            echo "Debugging - listing all instance profiles:"
            aws iam list-instance-profiles --query "InstanceProfiles[?contains(InstanceProfileName, 'ElasticBeanstalk')]"
            echo ""
            echo "Please create it manually using these commands:"
            echo "aws iam create-instance-profile --instance-profile-name ElasticBeanstalk-EC2-Role"
            echo "aws iam add-role-to-instance-profile --instance-profile-name ElasticBeanstalk-EC2-Role --role-name ElasticBeanstalk-EC2-Role"
            exit 1
          fi

      # Create new application version
      - name: Create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name docker-react \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=elasticbeanstalk-ap-southeast-1-185157186506,S3Key=dockerrun/$VERSION_LABEL.zip

      # Create or update environment
      - name: Create or Update environment
        run: |
          ENV_STATUS=$(aws elasticbeanstalk describe-environments \
            --application-name docker-react \
            --environment-names production \
             --query "Environments[0].Status" \
             --output text 2>/dev/null || echo "NONE")

           if [ "$ENV_STATUS" = "NONE" ] || [ "$ENV_STATUS" = "None" ] || [ "$ENV_STATUS" = "Terminated" ]; then
             echo "Environment not found or terminated. Creating production..."
             aws elasticbeanstalk create-environment \
               --application-name docker-react \
               --environment-name production \
               --solution-stack-name "64bit Amazon Linux 2023 v4.7.1 running Docker" \
               --version-label $VERSION_LABEL \
               --option-settings Namespace=aws:autoscaling:launchconfiguration,OptionName=IamInstanceProfile,Value=ElasticBeanstalk-EC2-Role Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance
           else
             echo "Environment exists (status: $ENV_STATUS). Updating production..."
             aws elasticbeanstalk update-environment \
               --environment-name production \
               --version-label $VERSION_LABEL
           fi

      # Cleanup old application versions (keep last 10)
      - name: Cleanup old application versions
        run: |
          VERSIONS=$(aws elasticbeanstalk describe-application-versions \
            --application-name docker-react \
            --query "ApplicationVersions[?Status=='PROCESSED'].VersionLabel" \
            --output text | tr '\t' '\n' | sort)

          COUNT=$(echo "$VERSIONS" | wc -l)

          if [ $COUNT -gt 10 ]; then
            DELETE=$(echo "$VERSIONS" | head -n -10)
            for v in $DELETE; do
              echo "Deleting old version: $v"
              aws elasticbeanstalk delete-application-version \
                --application-name docker-react \
                --version-label $v \
                --delete-source-bundle
            done
          else
            echo "No cleanup needed. Total versions: $COUNT"
          fi
